# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1b71956139ba9d77b9db16dd0a40e5f83ea1d7c6c8bd0b5c5d2788adb078507c124cc8c89d1e5c8995096be02d539436ea56fa3a1f68d5eaadebb7bdf2fdfbb

test:
  secret_key_base: 9f629922f8420c730ceec358b5ad3fdfacf6c4182621db75abddfcebbc742d92e7ff2877f39fd1359dd779e6678cd7b3d2535b154d74f64ef60bee42c899c1c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
